//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie_Info()
        {
            this.Show_Info = new HashSet<Show_Info>();
        }
    
        public int Movie_Id { get; set; }
        public string M_ID { get; set; }
        public string Movie_Name { get; set; }
        public string Movie_Description { get; set; }
        public Nullable<double> Movie_Rating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Show_Info> Show_Info { get; set; }
    }
}
