//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Info
    {
        public Customer_Info()
        {
            this.Booking_Details = new HashSet<Booking_Details>();
        }
    
        public string Customer_Id { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Password { get; set; }
        public int Phone_No { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Booking_Details> Booking_Details { get; set; }
    }
}
