//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Info
    {
        public int Payment_Id { get; set; }
        public string P_ID { get; set; }
        public int Ticket_Id { get; set; }
        public decimal Total_Price { get; set; }
        public string Mode { get; set; }
    
        public virtual Booking_Details Booking_Details { get; set; }
    }
}
