//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show_Info
    {
        public Show_Info()
        {
            this.Booking_Details = new HashSet<Booking_Details>();
        }
    
        public string Show_Id { get; set; }
        public string Theater_Id { get; set; }
        public string Movie_Id { get; set; }
        public System.DateTime Show_Date { get; set; }
        public System.TimeSpan Start_Time { get; set; }
        public decimal Price { get; set; }
    
        public virtual ICollection<Booking_Details> Booking_Details { get; set; }
        public virtual Movie_Info Movie_Info { get; set; }
        public virtual Theater_Info Theater_Info { get; set; }
    }
}
