//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theater_Info
    {
        public Theater_Info()
        {
            this.Employee_Info = new HashSet<Employee_Info>();
            this.Show_Info = new HashSet<Show_Info>();
        }
    
        public int Theater_Id { get; set; }
        public string Theater_Name { get; set; }
        public int Capacity { get; set; }
        public string Location { get; set; }
        public string T_ID { get; set; }
    
        public virtual ICollection<Employee_Info> Employee_Info { get; set; }
        public virtual ICollection<Show_Info> Show_Info { get; set; }
    }
}
