using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace WebApplication10
{
    public partial class Ticket_Cancellation : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            using (projectEntities context = new projectEntities())
            {
                GridView1.DataSource = (from b in context.Booking_Details
                                        join c in context.Customer_Info on b.Customer_Id equals c.Customer_Id
                                        where c.Customer_Id == 3
                                        select new
                                        {
                                            b.Show_Info.Theater_Info.Theater_Name,
                                            b.Show_Info.Movie_Info.Movie_Name,
                                            b.Show_Info.Show_Date,
                                            b.Show_Info.Start_Time,
                                            b.No_Of_Tickets,
                                            b.Ticket_Id
                                        }).ToList();
                GridView1.AutoGenerateDeleteButton = true;
                GridView1.DataBind();
            }
        }

        protected void GridView1_RowCommand(object sender, GridViewCommandEventArgs e)
        {
            if (e.CommandName == "Delete")
            {
                // get the categoryID of the clicked row
                int rowId = Convert.ToInt32(e.CommandArgument);
                // Delete the record 
                Response.Write(rowId);
                // Implement this on your own :) 
                Session["rowId"] = rowId;

            }

                
        }
        protected void GridView1_RowDeleting(object sender, GridViewDeleteEventArgs e)
        {
            int rowId = Int32.Parse(Session["rowId"].ToString());
            
            Response.Write(GridView1.Rows[rowId].Cells[1].Text);
            int tk_id=Int32.Parse(GridView1.Rows[rowId].Cells[6].Text);
            using (projectEntities context = new projectEntities())
            {
                Booking_Details ticket = (from b in context.Booking_Details
                                          where b.Ticket_Id == tk_id
                                          select b).FirstOrDefault();
                context.Booking_Details.Remove(ticket);
                context.SaveChanges();

                Response.Redirect("default.aspx");
            }

            
        }

        protected void GridView1_RowDataBound(object sender, GridViewRowEventArgs e)
        {
            if (e.Row.RowType == DataControlRowType.DataRow && e.Row.RowIndex != GridView1.EditIndex)
            {
                (e.Row.Cells[0].Controls[0] as LinkButton).Attributes["onclick"] = "return confirm('Do you want to delete this row?');";
            }
        }

    }
}