using Microsoft.Office.Interop.Outlook;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace WebApplication10
{
    public partial class Ticket_Cancellation : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            if (Session["Customer_Id"] == null)
            {
                Response.Redirect("~/User-Info/Log-In.aspx");
            }
            using (projectEntities1 context = new projectEntities1())
            {
                int customerId = Int32.Parse(Session["Customer_Id"].ToString());
                TimeSpan time = (DateTime.Now.AddHours(1) - DateTime.Today);

                GridView1.DataSource = (from b in context.Booking_Details
                                        join c in context.Customer_Info on b.Customer_Id equals c.Customer_Id
                                        join s in context.Seat_Details on b.Ticket_Id equals s.Ticket_Id
                                        where c.Customer_Id == customerId && b.Show_Info.Show_Date == DateTime.Today && b.Show_Info.Start_Time > time
                                        select new
                                        {
                                            b.Show_Info.Theater_Info.Theater_Name,
                                            b.Show_Info.Movie_Info.Movie_Name,
                                            b.Show_Info.Show_Date,
                                            b.Show_Info.Start_Time,
                                            b.No_Of_Tickets,
                                            s.Seat_No,
                                            b.Ticket_Id
                                        }).ToList();
                GridView1.AutoGenerateDeleteButton = true;
                GridView1.DataBind();

                GridView2.DataSource = (from b in context.Booking_Details
                                        join c in context.Customer_Info on b.Customer_Id equals c.Customer_Id
                                        join s in context.Seat_Details on b.Ticket_Id equals s.Ticket_Id
                                        where c.Customer_Id == customerId && b.Show_Info.Show_Date > DateTime.Now
                                        select new
                                        {
                                            b.Show_Info.Theater_Info.Theater_Name,
                                            b.Show_Info.Movie_Info.Movie_Name,
                                            b.Show_Info.Show_Date,
                                            b.Show_Info.Start_Time,
                                            b.No_Of_Tickets,
                                            s.Seat_No,
                                            b.Ticket_Id
                                        }).ToList();
                GridView2.AutoGenerateDeleteButton = true;
                GridView2.DataBind();
            }
        }

        protected void GridView1_RowCommand(object sender, GridViewCommandEventArgs e)
        {
            if (e.CommandName == "Delete")
            {
                int rowId = Convert.ToInt32(e.CommandArgument);
                Response.Write(rowId);
                Session["rowId"] = rowId;
            }

                
        }
        protected void GridView1_RowDeleting(object sender, GridViewDeleteEventArgs e)
        {   
            int rowId = Int32.Parse(Session["rowId"].ToString());
            int customerId = int.Parse(Session["Customer_Id"].ToString());
            Response.Write(GridView1.Rows[rowId].Cells[1].Text);
            int tk_id=Int32.Parse(GridView1.Rows[rowId].Cells[7].Text);
            using (projectEntities1 context = new projectEntities1())
            {

                Seat_Details seatNo = (from s in context.Seat_Details
                                 where s.Ticket_Id == tk_id
                                 select s).FirstOrDefault();

                Payment_Info payment = (from p in context.Payment_Info
                                  where p.Ticket_Id == tk_id
                                  select p).FirstOrDefault();

                var user = (from c in context.Customer_Info
                            where c.Customer_Id == customerId
                            select c).FirstOrDefault();

                Application OutlookApplication = new Application();


                MailItem message = (MailItem)OutlookApplication.CreateItem(OlItemType.olMailItem);

                MailAddress toAddress = new MailAddress(user.Email);

                Booking_Details ticket = (from b in context.Booking_Details
                                          where b.Ticket_Id == tk_id
                                          select b).FirstOrDefault();

                message.To = toAddress.ToString();
                message.Subject = "Confirm Cancellation";
                message.HTMLBody = "<div><h1>THANK YOU for using Let's book</h1>" + "<br/><br/>" + "Theater Name:" + "<br/><br/>" + ticket.Show_Info.Theater_Info.Theater_Name + "Movie:" + ticket.Show_Info.Movie_Info.Movie_Name + "<br/><br/>" + "Show Date:" + ticket.Show_Info.Show_Date + "<br/><br/>" + "Show Time:" + ticket.Show_Info.Start_Time + "<br/><br/>" + "No of Tickets:" + ticket.No_Of_Tickets + "<br/><br/>" + "Seat Numbers:" + seatNo.Seat_No + "<br/><br/>" + "Price:" + payment.Total_Price + "<br/><br/>" + "See you soon" + "</div>";
                message.BodyFormat = OlBodyFormat.olFormatHTML;

                
                context.Booking_Details.Remove(ticket);
                context.SaveChanges();

                message.Send();

                Response.Redirect("default.aspx");
            }
        }

        protected void GridView1_RowDataBound(object sender, GridViewRowEventArgs e)
        {
            if (e.Row.RowType == DataControlRowType.DataRow && e.Row.RowIndex != GridView1.EditIndex)
            {
                (e.Row.Cells[0].Controls[0] as LinkButton).Attributes["onclick"] = "return confirm('Do you want to delete this row?');";
            }
        }

        public void Signout_Click(object sender, EventArgs e)
        {
            FormsAuthentication.SignOut();
            Response.Write("Successfully logged out");
            Response.Redirect("~/User-Info/Log-In.aspx");
        }

        protected void GridView2_RowCommand(object sender, GridViewCommandEventArgs e)
        {
            if (e.CommandName == "Delete")
            {
                int rowId = Convert.ToInt32(e.CommandArgument);
                Response.Write(rowId);
                Session["rowId"] = rowId;
            }
        }

        protected void GridView2_RowDataBound(object sender, GridViewRowEventArgs e)
        {
            if (e.Row.RowType == DataControlRowType.DataRow && e.Row.RowIndex != GridView2.EditIndex)
            {
                (e.Row.Cells[0].Controls[0] as LinkButton).Attributes["onclick"] = "return confirm('Do you want to delete this row?');";
            }
        }

        protected void GridView2_RowDeleting(object sender, GridViewDeleteEventArgs e)
        {
            int rowId = Int32.Parse(Session["rowId"].ToString());

            Response.Write(GridView2.Rows[rowId].Cells[1].Text);
            int tk_id = Int32.Parse(GridView2.Rows[rowId].Cells[6].Text);
            using (projectEntities1 context = new projectEntities1())
            {
                Booking_Details ticket = (from b in context.Booking_Details
                                          where b.Ticket_Id == tk_id
                                          select b).FirstOrDefault();
                context.Booking_Details.Remove(ticket);
                context.SaveChanges();

                Response.Redirect("default.aspx");
            }
        }
    }
}